spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=hrms;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=1qaz!QAZ

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


# JWT Settings
jwt.secret=HVPXdylPq84tkxxA7g/BAuAsGr3za4S+1A626UA2Aq8=
jwt.expiration=3600
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=86400000

# Server Port
server.port=8080

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=your-username
spring.mail.password=your-password
spring.mail.properties.mail.smtp.starttls.enable=true
resetpasswordlink=http://localhost:3000/reset-password

userIdPrefix=USR
employeeIdPrefix=EMP

